name: Deploy

on:
    push:
        branches:
            - master
        
jobs:
    build:
        runs-on: windows-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x
                
            - name: Install MAUI Workload
              run: dotnet workload install maui
              
            - name: Restore
              run: dotnet restore
              working-directory: ./protex.hr
            
            - name: Build
              run: dotnet build -c Release -f:net8.0-windows10.0.19041.0
              working-directory: ./protex.hr
              
            - name: Decode Signing Certificate
              run: |
                echo "${{ secrets.SIGNING_CERTIFICATE_BASE_64_CONTENT }}" > cert.asc
                certutil -decode cert.asc cert.pfx
              
            - name: Install Signing Certificate
              run: certutil -user -p ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }} -Silent NoRoot -importpfx cert.pfx
              
            - name: Publish
              run: dotnet publish -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=${{ secrets.SIGNING_CERTIFICATE_THUMBPRINT }}
              working-directory: ./protex.hr
              
            - name: Upload
              uses: actions/upload-artifact@v4 
              with:
                name: Build
                path: | 
                    ./protex.hr/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.msix
                    ./protex.hr/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.pfx